server:
  port: 9090
  servlet:
    context-path: /product
    
    /Applications/Eclipse_2020-06.app/Contents/workspace
    
    /Users/geng9516/Applications/Eclipse_2020-06.app/Contents/workspace